# This container uses MongoDB shell version v5.0.6

version: '3.8'

services:
  mongodb:
    image: 'mongo'
    ports:
      - '8094:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootuser
      MONGO_INITDB_ROOT_PASSWORD: rootpass
    volumes:
      - data:/data
    container_name: 'mongodb'

volumes:
  data: {}
